package com.fh.domain;
// Generated Mar 25, 2016 11:08:13 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Classes generated by hbm2java
 */
public class Classes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7957747588700680694L;
	private Integer classId;
	private String className;
	private Set<Student> students = new HashSet<Student>(0);

	public Classes() {
	}

	public Classes(String className) {
		this.className = className;
	}

	public Classes(String className, Set<Student> students) {
		this.className = className;
		this.students = students;
	}

	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
