package com.fh.domain;
// Generated Mar 25, 2016 11:08:13 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private Integer personId;
	private String password;
	private String hobbies;
	private String email;
	private String name;
	private String gender;
	private Date birthday;

	public Person() {
	}

	public Person(String name, String gender) {
		this.name = name;
		this.gender = gender;
	}

	public Person(String password, String hobbies, String email, String name, String gender, Date birthday) {
		this.password = password;
		this.hobbies = hobbies;
		this.email = email;
		this.name = name;
		this.gender = gender;
		this.birthday = birthday;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getHobbies() {
		return this.hobbies;
	}

	public void setHobbies(String hobbies) {
		this.hobbies = hobbies;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

}
