package com.fh.domain;
// Generated Mar 27, 2016 10:33:23 AM by Hibernate Tools 4.3.1.Final

/**
 * Seller generated by hbm2java
 */
public class Seller implements java.io.Serializable {

	private Integer id;
	private String name;
	private String tel;
	private String address;
	private String website;
	private Integer star;
	private String business;

	public Seller() {
	}

	public Seller(String name, String tel, String address, String website, Integer star, String business) {
		this.name = name;
		this.tel = tel;
		this.address = address;
		this.website = website;
		this.star = star;
		this.business = business;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public Integer getStar() {
		return this.star;
	}

	public void setStar(Integer star) {
		this.star = star;
	}

	public String getBusiness() {
		return this.business;
	}

	public void setBusiness(String business) {
		this.business = business;
	}

}
